version: '3.7'

networks:
  test:
    name: fabric_test
    external: true
    driver: bridge

services:
  auditor:
    hostname: auditor.example.com
    container_name: auditor.example.com
    restart: always
    build:
      context: ./auditor
      dockerfile: ../Dockerfile
    volumes:
      - ./data/auditor:/var/fsc/data/auditor
      - ./auditor/conf:/conf:ro
      - ./keys:/var/fsc/keys:ro
    ports:
      - 9000:9000
    expose:
      - 9001
    networks:
      - test
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/api/v1/readyz"]
      interval: "5s"
      timeout: "1s"
      retries: 20

  issuer:
    hostname: issuer.example.com
    container_name: issuer.example.com
    restart: always
    build:
      context: ./issuer
      dockerfile: ../Dockerfile
    volumes:
      - ./data/issuer:/var/fsc/data/issuer
      - ./issuer/conf:/conf:ro
      - ./keys:/var/fsc/keys:ro
    ports:
      - 9100:9000
    expose:
      - 9101  
    networks:
      - test
    depends_on:
      - auditor

  owner1:
    hostname: owner1.example.com
    container_name: owner1.example.com
    restart: always
    build:
      context: ./owner
      dockerfile: ../Dockerfile
    volumes:
      - ./data/owner1:/var/fsc/data/owner1
      - ./owner/conf/owner1:/conf:ro
      - ./keys:/var/fsc/keys:ro
    ports:
      - 9200:9000
    expose:
      - 9201
    networks:
      - test
    depends_on:
      - auditor

  owner2:
    hostname: owner2.example.com
    container_name: owner2.example.com
    restart: always
    build:
      context: ./owner
      dockerfile: ../Dockerfile
    volumes:
      - ./data/owner2:/var/fsc/data/owner2
      - ./owner/conf/owner2:/conf:ro
      - ./keys:/var/fsc/keys:ro
    ports:
      - 9300:9000
    expose:
      - 9301
    networks:
      - test
    depends_on:
      - auditor

  swagger-ui:
      image: swaggerapi/swagger-ui
      container_name: swagger-ui
      ports:
          - '8082:8080'
      environment:
          - URL=/swagger.yaml
      volumes:
          - ./swagger.yaml:/usr/share/nginx/html/swagger.yaml
